### ISSUE TITLE
Totally unrelated

### ISSUE THREAD

**Issue by iamtejas28** [palashcode/learn_git#1]
@palashcode  Did you manage to download the private videos from ravindra sir's website?
https://github.com/rg3/youtube-dl/issues/10541

How should I do it?
Currently it seems like i have to go into each course, sub course, topic, subtopic and then download one video per subtopic.
How did you do the batch download?

**Comment by palashcode** [comment]
use this 
until youtube-dl -c -f http-360p -o "%(autonumber)s-%(title)s.%(ext)s" --batch-file=filename --referer http://eclassesbyravindra.com/ ; do sleep 10; done

To make the batch file with all the url you can write a python script which I don't know how to write  you can search it  
And please don't distribute the videos.

**Comment by palashcode** [comment]
@vivekm7 @iamtejas28
Make the batch file using python script to crawl website
video url can be found using view page source then search for this type of url "http://player.vimeo.com/"
put batch file name in this command
until youtube-dl -c -f http-360p -o "%(autonumber)s-%(title)s.%(ext)s" --batch-file=file-name --referer http://eclassesbyravindra.com/ ; do sleep 10; done

**Comment by iamtejas28** [comment]
@palashcode Could you provide me with your py scraper?(I am not asking for credentials, I already signed up but I can't always watch the videos online. So i just need your help please!)

**Comment by palashcode** [comment]
I don't have any script I did it manually. But you should search some script and try to modify that it will save a lot of time. This can help https://automatetheboringstuff.com/chapter11/

**Comment by iamtejas28** [comment]
Okay. i am not good at python.......anyways, thank you :) 👍
